[tool.pdm]

[project]
name = "saldo-dalin-ws"
version = "0.0.1"
description = ""
authors = [
    {name = "Kristoffer Andersson", email = "kod.kristoff@gmail.com"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}
